<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Transitional//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-transitional.dtd">
<html xmlns="http://www.w3.org/1999/xhtml">
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<title>饭店网友情提示</title>
<style type="text/css">
body {
	overflow: hidden;
	background: #FE6833 !important;
}
#oldie {
	color: #FFF;
	left: 50%;
	margin-left: -150px;
	margin-top: -300px;
	width: 560px;
	top: 50%;
	text-align: center;
	position: absolute;
	display: block;
	text-align: left;
	line-height: 180%
}
#oldie a {
	text-decoration: underline;
	color: #FFF;
	font-weight: bold;
}
#oldie a:hover {
	color: #333;
	text-decoration: underline
}
.kill-ie6 {
	text-indent: -999em;
	width: 350px;
	height: 354px;
	background: url(../../common/images/killie6.png) no-repeat;
	display: block;
	margin-bottom: 10px;
}
</style>
</head>

<body>
<div id="oldie">
  <span class="kill-ie6">kill ie6</span>
  <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;您正在使用的IE6浏览器可能存在漏洞，超过95%的饭店网用户已经把浏览器升级到更高版本或者使用其他浏览器。</p>
  <p>&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;&nbsp;为了您能正常访问饭店网，请升级您的IE浏览器(<a href="http://www.microsoft.com/zh-cn/download/details.aspx?id=2">IE7</a>｜<a href="http://www.microsoft.com/zh-cn/download/details.aspx?id=43"> IE8</a>｜<a href="http://www.microsoft.com/zh-cn/download/details.aspx?id=13950">IE9</a>)，或者使用<a href="http://www.google.cn/intl/zh-CN/chrome/browser/">Google Chrome</a>｜<a href="http://www.firefox.com.cn/download/">Firefox</a>浏览器。 立刻升级吧！</p>
</div>
</body>
</html>
