<?php include_once dirname(__FILE__).'/../include/page_head.phtml';?>
<div class='wrapper'>
	<?php include_once(dirname(__FILE__).'/../include/page_info.phtml');?>
	<div class='page_nav'>
		<div class='page_info'>编辑菜品</div>
		
		<div class='page_now'></div>
	</div>	

<form id='modify_form' method='post' action='<?php echo $this->scriptUrl;?>items/doedit' target='_self' enctype='multipart/form-data'>
<table class='edit_table' cellspacing='1'>
	<tbody>
		<tr>
			<td width='15%' class='center left'>
				菜品名
			</td>
			<td class='text right'>
				<?php echo $this->data['ItemName'];?>
			</td>
			<td width='15%' class='center left'>
				设置
			</td>
			<td class='text right'>
				<?php echo $this->Checkbox(array(
					'name' => 'IsRec',
					'user_value' => $this->extend['IsRec'],
					'value' => '1',
					'label' => '设为推荐菜'	
					));?>				
			</td>
		</tr>

		<tr>
			<td width='15%' class='center left'>
				LOGO（小）<br />
				135x100
			</td>
			<td class='text right' colspan='3'>
				<span id='item_logo_small'>上传LOGO</span>
				<span id='item_logo_url' href='<?php echo $this->item_logo_url;?>'>点击浏览</span>
			</td>
		</tr>
		<tr>
			<td width='15%' class='center left'>
				LOGO（大，首页推荐）<br />
				186x100
			</td>
			<td class='text right' colspan='3'>
				<span id='item_logo_big'>上传LOGO</span>
				<span id='item_logo_url_big' href='<?php echo $this->item_logo_big_url;?>'>点击浏览</span>
			</td>
		</tr>
		<tr>
			<td colspan='4' class='center bottom'>
				<input type='submit' id='submit' value='确定' />
				<input type='button' id='back' value='返回' onclick="javascript:history.back()" />
				<input type='hidden' name='ItemGuid' value='<?php echo $this->data['ItemGuid'];?>' id='ItemGuid' />	
			</td>
		</tr>
	</tbody>
</table>
</form>
</div>
<script type='text/javascript'>
var uploader = null;
var uploader2 = null;
var uploader3 = null;

$(function(){

	uploader = new AjaxUpload('#item_logo_small', {
		action: '<?php echo $this->baseUrl;?>files/upload/item',
		name: 'myfile',
		data: {
			'ItemGuid': '<?php echo $this->data['ItemGuid'];?>',
			'VendorGuid': '<?php echo $this->data['VendorGuid'];?>'
		},
		autoSubmit: true,
		onSubmit: function(file,ext){
		},
		onComplete: function(file, upload_response){
			tmp = eval(upload_response);
			Src = tmp[0];
			$('#item_logo_url_small').attr('href', Src);
			alert('上传成功');
		}
	});	

	uploader2 = new AjaxUpload('#item_logo_small', {
		action: '<?php echo $this->baseUrl;?>files/upload/itembig',
		name: 'myfile',
		data: {
			'ItemGuid': '<?php echo $this->data['ItemGuid'];?>',
			'VendorGuid': '<?php echo $this->data['VendorGuid'];?>'
		},
		autoSubmit: true,
		onSubmit: function(file,ext){
		},
		onComplete: function(file, upload_response){
			tmp = eval(upload_response);
			Src = tmp[0];
			$('#item_logo_url_big').attr('href', Src);
			alert('上传成功');
		}
	});	

	$('#item_logo_url, #item_logo_url_big, #item_logo_url_spec').click(function(){
		window.open($(this).attr('href'));
	});		
});
</script>
<?php include_once dirname(__FILE__).'/../include/page_foot.phtml';?>