<?php if($_SERVER[REQUEST_URI]=='/'||$_SERVER[REQUEST_URI]=='/index/home'){?>
<style type='text/css'>
#links{
	border-top:1px solid #E1E1E1;
	margin-top:10px;
}
#links h3 {
    color: #000000;
    font-size: 10pt;
}
#links p {
    line-height: 20px;
    padding: 5px;
}
#links p a {
    color: #666666;
    font-size: 9pt;
    margin-right: 6px;
}


#adl {
    background: url("<?php echo $this->baseUrl?>common/images/left.png?v=1") no-repeat scroll left top transparent;
    height: 345px;
    width: 175px;
    cursor:pointer;
    display:none;
}
.ad .closeIco {
    width:18px;
    height:20px;
}
.ad .closeIco a {
    background: url("<?php echo $this->baseUrl?>common/images/closeIco.jpg") no-repeat scroll left top transparent;
    float: right;
    height: 11px;
    width: 11px;
}
.ad p {
    color: #B54800;
    float: left;
    font-size: 12px;
    line-height: 18px;
    padding: 102px 12px 0;
    text-align: center;
    width: 86px;
}

</style>
<div id="adl" class="ad" style="top: 170px; position: fixed; left: 10px;">
   <div class="closeIco" style="float: left;margin-left:10px"></div>
</div>

<div class="row">
<div class="twelvecol">
<div class="bmodule" id="links">
<h3 class="caption">+ 友情链接</h3>
<p>
<a target="_blank" href="http://suzhou.doomii.com/">苏州外卖网</a>
<a target="_blank" href="http://www.jilinfood.net/">吉林食品网</a>
<a target="_blank" href="http://www.jujiameishi.com/">快乐生活一点通</a>
<a target="_blank" href="http://www.117dc.com/">苏州外卖</a>
<a target="_blank" href="http://www.gz-food.net/">广州美食网</a>
<a target="_blank" href="http://www.fz513.com/">福州网上订餐</a>
</p>
</div>
</div>
</div>


<script type="text/javascript">
$(document).ready(function(){
	$("#adl").click(function(){
		window.location.href="http://szdsh.fandian.com/announce/%E5%9C%A3%E8%AF%9E%E7%8B%82%E6%AC%A2%E5%AD%A3--%E6%BB%A1100%E9%80%8150";
	});
	$("#adl .closeIco").click(function(event){
		$('#adl').hide();
		event.stopPropagation();
	});
})
</script>
<?php }?>