<?php include_once dirname(__FILE__).'/../include/page_head.phtml';?>
<div class='wrapper'>
	<?php include_once(dirname(__FILE__).'/../include/page_info.phtml');?>
	<div class='page_nav'>
		<div class='page_info'>编辑系统用户</div>
		
		<div class='page_now'></div>
	</div>	

<form method='post' action='<?php echo $this->scriptUrl;?>sysusers/doedit' target='_self'>	
<table class='edit_table' cellspacing='1'>
	<tbody>
		<tr>
			<td width='15%' class='center left'>
				用户名
			</td>
			<td width='35%' class='text right'>
				<input type='text' name='Username' id='Username' value='<?php echo $this->data['Username'];?>' /> <span class='error'><?php echo $this->error['Username'];?></span>
			</td>
			<td width='15%' class='center left'>
				密码
			</td>
			<td width='35%' class='text right'>
				<input type='password' name='Password' id='Password' value='<?php echo $this->data['Password'];?>' /><span class='error'><?php echo $this->error['Password'];?></span>
			</td>
		</tr>
		
		<tr>
			<td width='15%' class='center left'>
				权限
			</td>
			<td colspan='3' class='text right'>
				<ol class='s_rights'>
				<?php foreach ($this->acls as $acl=>$name) { ?>
				<li><?php echo $this->Checkbox(array(
						'name' => 'acls',
						'type' => 'array',
						'value' => $acl,
						'user_value' => (is_array($this->u_acls) && in_array($acl, $this->u_acls)) ? $acl : '',
						'label' => $name['name']
						));?></li>
				<?php } ?>
				</ol>
			</td>
		</tr>
		
		<tr>
			<td colspan='4' class='center bottom'>
				<input type='submit' id='submit' value='确定' />
				<input type='hidden' name='AutoId' value='<?php echo $this->data['AutoId'];?>' id='AutoId' />			
			</td>
		</tr>
	</tbody>
</table>
</form>
</div>
<?php include_once dirname(__FILE__).'/../include/page_foot.phtml';?>