<?php include_once(dirname(__FILE__).'/../include/page_head.phtml');?>
<div class='wrapper'>
	<?php include_once(dirname(__FILE__).'/../include/page_info.phtml');?>
	<div class='page_nav'>
		<div class='page_info'>网上支付查询</div>
		
		<div class='page_now'></div>
	</div>	

<form action='<?php echo $this->scriptUrl;?>pay/check' id='homepage_form'>
<table cellspacing='1' class='edit_table'>
<tbody>
	<tr>
		<td class='center left' width='15%'>网单订单号：</td>
		<td class='right'>
			 <input type="text" name="OrderId" id="OrderId" value="<?php echo $this->request['OrderId'];?>" size='40' />
		</td>
	</tr>
	<?php if ($this->data) { ?>
	<tr>
		<td class='center left' width='15%'>交通银行查询结果：</td>
		<td class='right'>
			 <?php echo $this->data['comm'];?>
		</td>
	</tr>	
	<tr>
		<td class='center left' width='15%'>招商银行查询结果：</td>
		<td class='right'>
			 <?php echo $this->data['cmb'];?>
		</td>
	</tr>	
	<?php } ?>
	<tr>
		<td class='center left' colspan='2'>
			<input type='submit' name='go' id='go' value=' 提 交 (s) ' accesskey='s' />
			<input type='hidden' name='do_search' value='1' />
		</td>
	</tr>
</tbody>
</table>
</form>

</div>
<?php include_once(dirname(__FILE__).'/../include/page_foot.phtml');?>