<?php include_once dirname(__FILE__).'/../include/page_head.phtml';?>
<div class='wrapper'>
	<?php include_once(dirname(__FILE__).'/../include/page_info.phtml');?>
	<div class='page_nav'>
		<div class='page_info'>编辑投票</div>
		
		<div class='page_now'></div>
	</div>	

<form method='post' action='<?php echo $this->scriptUrl;?>votes/doedit' target='_self'>	
<table class='edit_table' cellspacing='1'>
	<tbody>
		<tr>
			<td width='15%' class='center left'>
				投票标题
			</td>
			<td class='text right'>
				<input type='text' size='70' name='VoteTitle' id='VoteTitle' value='<?php echo $this->data['VoteTitle'];?>' /> <span class='error'><?php echo $this->error['VoteTitle'];?></span>
			</td>
			<td width='15%' class='center left'>
				发布时间
			</td>
			<td class='text right'>
				<input type='text' size='20' name='' id='AddTime' value='<?php echo $this->Dt($this->data['AddTime'], 'date');?>' /> 
			</td>
		</tr>
		<tr>
			<td width='15%' class='center left'>
				设置
			</td>
			<td class='text right'>
				<?php echo $this->Checkbox(array(
						'name' => 'PubFlag',
						'value' => '1',
						'user_value' => $this->data['PubFlag'],
						'label' => '发布到前台'
						));?>
			</td>
			<td width='15%' class='center left'>
				是否多选投票
			</td>
			<td width='35%' class='text right'>
				<?php echo $this->Checkbox(array(
						'name' => 'IsMultiChoice',
						'value' => '1',
						'user_value' => $this->data['IsMultiChoice'],
						'label' => '设为多选投票'
						));?>
			</td>
		</tr>			
		<tr>
			<td width='15%' class='center left'>
				所属模块
			</td>
			<td width='35%' class='text right'>
				<?php echo $this->Select(Msd_Functions::ArrayMerge(array(
			'0' => '* 请选择 *'
			), $this->Modules), 'Module', $this->data['Module']);?> <span class='error'><?php echo $this->error['Module'];?></span>
			</td>
			<td width='15%' class='center left'>
				排序
			</td>
			<td width='35%' class='text right'>
				<input type='text' size='4' maxlength='4' name='OrderNo' id='OrderNo' value='<?php echo $this->data['OrderNo'];?>' /><span class='error'><?php echo $this->error['OrderNo'];?></span>
			</td>
		</tr>
		<tr>
			<td width='15%' class='center left'>
				简介 
			</td>
			<td colspan='3' class='text right'>
				<textarea name='Intro' id='Intro'  class='p_kindeditor'><?php echo htmlspecialchars($this->data['Intro']);?></textarea>
			</td>
		</tr>		
		<tr>
			<td colspan='4' class='center bottom'>
				选项
			</td>
		</tr>
		<?php 
		if ($this->error['choices']) {
		?>		
		<tr>
			<td colspan='4' class='center left'>
				<span class='error'><?php echo $this->error['choices'];?></span>
			</td>
		</tr>
		<?php 
		}
		?>
		<?php 
		for($i=0;$i<10;$i++) {
		?>
		<tr>
			<td width='15%' class='center left'>
				<?php echo $i+1;?> 
			</td>
			<td colspan='3' class='text right'>
				<input size='120' type='text' name='choice_<?php echo $i;?>' id='choice_<?php echo $i;?>' value='<?php echo $this->choices[$i]['ChoiceTitle'];?>' />
				选择数：<input type='text' size='4' name='choosed_<?php echo $i;?>' id='choosed_<?php echo $i;?>' value='<?php echo (int)$this->choices[$i]['Choosed'];?>' />
			</td>
		</tr>				
		<?php 
		}
		?>
		<tr>
			<td colspan='4' class='center bottom'>
				<input type='submit' id='submit' value='确定' />
				<input type='button' id='back' value='返回' onclick="javascript:history.back()" />
				<input type='hidden' name='AutoId' value='<?php echo $this->data['AutoId'];?>' id='AutoId' />		
			</td>
		</tr>
	</tbody>
</table>
</form>
</div>
<script type='text/javascript'>

$(function(){

	KindEditor.ready(function(K) {
		editor = K.create('textarea[name="Intro"]', {
			uploadJson : '<?php echo $this->baseUrl;?>fadmin/kind-editor/upload',
			allowFileManager : false,
			items : [
			         'source', '|', 'undo', 'redo', '|', 'preview', 'print', 'code', 'cut', 'copy', 'paste',
			         'plainpaste', 'wordpaste', '|', 'justifyleft', 'justifycenter', 'justifyright',
			         'justifyfull', 'insertorderedlist', 'insertunorderedlist', 'indent', 'outdent', 'subscript',
			         'superscript', 'clearhtml', 'quickformat', 'selectall', '|', 'fullscreen', '/',
			         'formatblock', 'fontname', 'fontsize', '|', 'forecolor', 'hilitecolor', 'bold',
			         'italic', 'underline', 'strikethrough', 'lineheight', 'removeformat', '|', 'image', 
			         'insertfile', 'table', 'hr', 'emoticons', 'baidumap', 'pagebreak',
			         'anchor', 'link', 'unlink', '|', 'about'
			        ]
		});
	});
});
</script>
<?php include_once dirname(__FILE__).'/../include/page_foot.phtml';?>