<?php include_once(dirname(__FILE__).'/../include/page_head.phtml');?>
<div class='wrapper'>
	<?php include_once(dirname(__FILE__).'/../include/page_info.phtml');?>
	<div class='page_nav'>
		<div class='page_info'>浏览留言</div>
		
		<div class='page_now'></div>
	</div>	
	
<form>
<table cellspacing='1' class='search_table'>
<tbody>
<tr>
	<td >
	搜索：<?php echo $this->Select(array(
			'' => '* 请选择 *',
			'Content' => '留言内容',
			'ReplyContent' => '回复内容',
			), 'search_key', $this->request['search_key']);?><input type='text' name='search_val' id='search_val' value='<?php echo $this->request['search_val'];?>' />
	&nbsp;
	前台是否显示：
	<?php echo $this->Select(array(
			'' => '* 请选择 *',
			'0' => '前台不显示',
			'1' => '前台显示'
			), 'DisplayFlag', $this->request['DisplayFlag']);?>
	&nbsp;
	排序：<?php echo $this->Select(array(
			'' => '* 请选择 *',
			'CreateTime' => '留言时间',
			'ReplyTime' => '回复时间',
			), 'order_key', $this->request['order_key']);?>
		<input type='submit' name='btn_search' id='btn_search' value=' 搜 索 (s) ' accesskey='s' />
	</td>
</tr>
</tbody>
</table>
</form>

<table cellspacing='1' class='list_table'>
<thead>
	<tr class='ths'>
		<th width='5%'>序号</th>
		<th width='25%'>留言内容</th>
		<th width='5%'>用户</th>
		<th width='8%'>手机号</th>
		<th width='10%'>留言时间</th>
		<th width='8%'>IP地址</th>
		<th width='7%'>前台显示</th>
		<th width='6%'>排序值</th>
		<th width='8%'>回复时间</th>
		<th width='10%'>回复内容</th>
		<th width='8%'>操作</th>
	</tr>
</thead>
<tbody class='datalist'>
<?php if (count($this->rows)>0) { ?>
<?php 
foreach ($this->rows as $row) { 
?>
<tr class='c<?php echo fmod($row['_seq'], 2);?>'>
	<td width='50'><?php echo $row['_seq'];?></td>
	<td class='left'>
		<?php echo $row['Content'];?>
	</td>
	<td><?php echo $row['CustGuid'] ? $row['Username'] : '匿名用户';?></td>
	<td><?php echo $row['Phone'];?></td>
	<td><?php echo $this->Dt($row['CreateTime']);?></td>
	<td><?php echo $row['IpAddress'];?></td>
	<td><?php echo $row['DisplayFlag'] ? '<span style="color:green; font-weight: bold;">是</span>' : '<span class="error err">否</span>';?></td>
	<td><?php echo $row['OrderNo'];?></td>
	<td><?php echo $row['ReplyTime'] ? $this->Dt($row['ReplyTime']) : '--';?></td>
	<td>
		<?php echo $row['ReplyContent'] ? $row['ReplyContent'] : '--';?>
	</td>
	<td>
		<a href='<?php echo $this->scriptUrl;?>feedback/edit?AutoId=<?php echo $row['AutoId'];?>'>修改</a>
		<a href='<?php echo $this->scriptUrl;?>feedback/del?AutoId=<?php echo $row['AutoId'];?>' rel='delete'>删除</a>
	</td>
</tr>
<?php } ?>
<?php } else { ?>
<tr class='c1'>
	<td colspan='10' class='center'>
		<span class='error'>暂无数据</span>
	</td>
</tr>
<?php } ?>
</tbody>
<tfoot>
	<tr>
		<td colspan='10'>
			<div class='pager'><?php echo $this->page_links;?></div>
		</td>
	</tr>
</tfoot>
</table>

</div>

<?php include_once(dirname(__FILE__).'/../include/page_foot.phtml');?>