<?php include_once(dirname(__FILE__).'/../include/page_head.phtml');?>
<div class='wrapper'>
	<?php include_once(dirname(__FILE__).'/../include/page_info.phtml');?>
	<div class='page_nav'>
		<div class='page_info'>修改个人密码</div>
		
		<div class='page_now'></div>
	</div>	
<?php if ($this->message) { ?>
<h3><?php echo $this->message;?></h3>
<?php } ?>

<form method='post' action='<?php echo $this->scriptUrl;?>self' id='homepage_form'>
<table cellspacing='1' class='edit_table'>
<tbody>
	<tr>
		<td class='center left' width='15%'>新密码：</td>
		<td class='right' colspan='2'>
			<input type='password' name='password' id='password' value='<?php echo $this->request['password'];?>' /> 
			<span class='error'><?php echo $this->error['password'];?></span>
		</td>
	</tr>
	<tr>
		<td class='center left' width='15%'>确认新密码：</td>
		<td class='right' colspan='2'>
			<input type='password' name='password2' id='password2' value='<?php echo $this->request['password2'];?>' />
			<span class='error'><?php echo $this->error['password2'];?></span>
		</td>
	</tr>

	<tr>
		<td class='center left' colspan='3'>
			<input type='submit' name='go' id='go' value=' 提 交 (s) ' accesskey='s' />
		</td>
	</tr>
</tbody>
</table>
</form>

</div>
<?php include_once(dirname(__FILE__).'/../include/page_foot.phtml');?>