<div class='wrapper'>
<table cellspacing='1' class='list_table'>
<thead>
	<tr class='ths'>
		<th colspan='10'>
		订单号：<?php echo $this->order['OrderId'];?>
		</th>
	</tr>
	<tr class='ths'>
		<th width='10%'>序号</th>
		<th width='20%'>状态ID</th>
		<th width='20%'>状态名称</th>
		<th width='20%'>时间</th>
		<th width='20%'>
		操作员
		</th>
	</tr>
</thead>
<tbody class='datalist'>
<?php if (count($this->rows)>0) { ?>
<?php 
$i = 1;
foreach ($this->rows as $row) { 
?>
<tr class='c<?php echo fmod($i, 2);?>'>
	<td width='50'><?php echo $i++;?></td>
	<td><?php echo $row['StatusId'];?></td>
	<td><?php echo $row['StatusName'];?></td>
	<td><?php echo $this->Dt($row['AddTime'], 'short_datetime');?></td>
	<td><?php echo $row['AddUser'];?></td>
</tr>
<?php } ?>
<?php } else { ?>
<tr class='c1'>
	<td colspan='16' class='center'>
		<span class='error'>暂无数据</span>
	</td>
</tr>
<?php } ?>
</tbody>
</table>

</div>