<li><a href='<?php echo $this->scriptUrl;?>profile'>我的个人资料</a></li>
<!-- <li><a href='<?php echo $this->scriptUrl;?>addressbook'>我的地址</a></li> -->
<li><a href='<?php echo $this->scriptUrl;?>feedback'>我的留言</a></li>
<li><a href='<?php echo $this->scriptUrl;?>order'>我的订单</a></li>
<li><a href='<?php echo $this->scriptUrl;?>favorites/vendors'>我收藏的餐厅</a></li>

<!--
<li><a href='<?php echo $this->scriptUrl;?>favorites/items'>我收藏的美味</a></li>
-->
