<?php include_once(dirname(__FILE__).'/../include/page_head.phtml');?>
<div class='wrapper'>
	<?php include_once(dirname(__FILE__).'/../include/page_info.phtml');?>
	<div class='page_nav'>
		<div class='page_info'>浏览地标</div>
		
		<div class='page_now'></div>
	</div>	
	
<form>
<table cellspacing='1' class='search_table'>
<tbody>
<tr>
	<td >
	搜索：<?php echo $this->Select(array(
			'' => '* 请选择 *',
			'CoordName' => '地标名',
			'RegionName' => '区域名',
			'CoordName' => '地标名',
			), 'search_key', $this->request['search_key']);?><input type='text' name='search_val' id='search_val' value='<?php echo $this->request['search_val'];?>' />
	&nbsp;
	所属区域：
	<?php echo $this->Select(
			Msd_Functions::ArrayMerge(array(
					'' => '* 请选择 *'
					), $this->regions)
			, 'Region', $this->request['Region']);?>
	&nbsp;
	排序：<?php echo $this->Select(array(
			'' => '* 请选择 *',
			'c.CoordName' => '地标名',
			'c.AddTime' => '添加时间',
			), 'order_key', $this->request['order_key']);?>
		<input type='submit' name='btn_search' id='btn_search' value=' 搜 索 (s) ' accesskey='s' />
	</td>
</tr>
</tbody>
</table>
</form>

<form method='post' action='<?php echo $this->scriptUrl;?>attachment/actions' id='form_attach_list'>
<table cellspacing='1' class='list_table'>
<thead>
	<tr class='ths'>
		<th width='5%'>序号</th>
		<th width='20%'>地标名</th>
		<th width='10%'>经度</th>
		<th width='10%'>纬度</th>
		<th width='10%'>百度经度</th>
		<th width='10%'>百度纬度</th>
		<th width='10%'>所属区域</th>
		<th></th>
	</tr>
</thead>
<tbody class='datalist'>
<?php if (count($this->rows)>0) { ?>
<?php 
foreach ($this->rows as $row) { 
?>
<tr class='c<?php echo fmod($row['_seq'], 2);?>'>
	<td width='50'><?php echo $row['_seq'];?></td>
	<td class='left'><?php echo $row['CoordName'];?></td>
	<td><?php echo $row['Longitude'];?></td>
	<td><?php echo $row['Latitude'];?></td>
	<td><span id='blng_<?php echo $row['CoordGuid'];?>'><?php echo $row['Baidu_Longitude'];?></span></td>
	<td><span id='blat_<?php echo $row['CoordGuid'];?>'><?php echo $row['Baidu_Latitude'];?></span></td>
	<td><?php echo $row['RegionName'];?></td>
	<td>
		<a href='<?php echo $this->scriptUrl;?>coord/edit?CoordGuid=<?php echo $row['VendorGuid'];?>'>修改</a>
		<a href='javascript:void(0);' coord='<?php echo $row['CoordGuid'];?>' lng='<?php echo $row['Longitude'];?>' lat='<?php echo $row['Latitude'];?>' class='gotbaidu'>获取百度经纬度</a>
	</td>
</tr>
<?php } ?>

<?php } else { ?>
<tr class='c1'>
	<td colspan='10' class='center'>
		<span class='error'>暂无数据</span>
	</td>
</tr>
<?php } ?>
<tr class='c1'>
	<td colspan='10' class='center'>
		<a class='error' id='batch_got'>批量获取本页百度经纬度</a>
	</td>
</tr>
</tbody>
<tfoot>
	<tr>
		<td colspan='10'>
			<div class='pager'><?php echo $this->page_links;?></div>
		</td>
	</tr>
</tfoot>
</table>
</form>
</div>
<script type="text/javascript" src="http://api.map.baidu.com/api?v=1.3"></script>
<script type="text/javascript" src="http://dev.baidu.com/wiki/static/map/API/examples/script/convertor.js"></script>
<script type='text/javascript'>
var ii = 0;
var coords = [];
var ctimer = null;

function batch_gotit()
{
	if (ii<coords.length) {
		$('a.gotbaidu').eq(ii).trigger('click');
		ii++;
	} else {
		ii = 0;
		coords = [];
		clearInterval(ctimer);
	}
}

$(function(){
	$('#btnDel').click(function(){
		return confirm('确定？');
	});

	$('a.gotbaidu').click(function(){
		var lng = parseFloat($(this).attr('lng'));
		var lat = parseFloat($(this).attr('lat'));
		var CoordGuid = $(this).attr('coord');

		var gpsPointer = new BMap.Point(lng, lat);
		BMap.Convertor.translate(gpsPointer, 0, function(point){
			blng = point.lng;
			blat = point.lat;

			$.post(BASE_URL+'fadmin/coord/forbaidu', {
				'CoordGuid': CoordGuid,
				'lng': blng,
				'lat': blat
			}, function(r){
				$('#blng_'+CoordGuid).text(blng);
				$('#blat_'+CoordGuid).text(blat);
				
			}, 'json');
		});
	});

	$('a#batch_got').click(function(){
		alert('点击确定开始，整个过程大约持续一分钟');
		coords = [];
		$('a.gotbaidu').each(function(){
			coords.push($(this).attr('CoordGuid'));
		});

		ctimer = setInterval('batch_gotit()', 3000);
	});
});
</script>
<?php include_once(dirname(__FILE__).'/../include/page_foot.phtml');?>