<?php Msd_Output::prepareHtml();?>
<?php echo '<'.'?xml version="1.0" encoding="utf-8"?'.'>'."\n";?>
<!DOCTYPE html>
<html>
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="expires" content="Wed, 26 Feb 1997 08:21:57 GMT" />
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="Cache-Control" content="no-cache" />
<title>For CSharp</title>
<meta http-equiv="Content-Language" content="zh-CN" />
<meta name="MSSmartTagsPreventParsing" content="true" />
<meta http-equiv="imagetoolbar" content="no" />
<meta name="author" content="无锡市汇洋科技开发有限公司" />
<meta name="copyright" content="无锡市汇洋科技开发有限公司" />
<link type="text/css" rel="stylesheet" href="<?php echo $this->baseUrl;?>css/jquery-ui.css" media="all" />
<link rel="stylesheet" href="<?php echo $this->baseUrl;?>css/jquery.tooltip.css" type="text/css" />
<style type="text/css">
body { font-size: 11px; font-family: tahoma,arial; background: #eee; margin: 0px; padding: 0px; }
#wrapper { width: 100%; margin: 0px auto; padding: 0px; border-bottom: 1px solid #aaa; }
#header { background: #fff; height: 30px; line-height: 30px; padding-left: 10px; }
#main { width: 100%; background: #fff; border-bottom: 1px solid #aaa; }
#widget { width: 250px; border-left: 1px solid #aaa; border-left: 1px solid #aaa; background: #efefef; float: right; }
#map { float: left; border-left: 1px solid #aaa; }

input[type="text"] { border: 1px solid #888; background; #fff; padding: 2px; }
</style>
</head>

<body class="container" id='body_baidu'>
<div id='wrapper'>
	<div id='header'>地址：<input type='text' class='input' id='keywords' name='keywords' /> <input type='button' id='btnSearch' value='搜索(s)' accesskey='s' /></div>
	<div id='main'>
		<div id='map'></div>
		<div id='widget'></div>
	</div>
</div>
<script type='text/javascript' charset='utf-8' src='<?php echo $this->jsUrl;?>jquery/jquery.min.js'></script>
<script type='text/javascript' charset='utf-8' src='<?php echo $this->jsUrl;?>jquery/jquery-ui.min.js'></script>
<script type='text/javascript'>
var bmap = null;
var baiduLoaded = false;
var bac = null;
var bs = null;
var CDATA = {
	'lat':31.311701,
	'lng': 120.625419	
};

function setCity(City, Level)
{
	if (bmap) {
		bmap.centerAndZoom(City, Level);
	}
}

function baiduMapCallback()
{
	bpointer = new BMap.Point(CDATA.lng, CDATA.lat);

	bmap = new BMap.Map('map');
	bmap.addControl(new BMap.NavigationControl({anchor: BMAP_ANCHOR_TOP_RIGHT, offset: new BMap.Size(10, 10)}));
	bmap.centerAndZoom(bpointer, 13);
	bmap.enableScrollWheelZoom();

	bac = new BMap.Autocomplete({
		'input': 'keywords',
		'location': bmap
	});
	bac.addEventListener('onconfirm', function(e){
		$('#btnSearch').trigger('click');
	});

	bs = new BMap.LocalSearch(bmap, {
		'renderOptions': {
			'map': bmap,
			'panel': 'widget'
		}
	});
}

function resizeDivs()
{
	wh = parseInt($(window).height());
	hh = parseInt($('#header').height());
	$('#map, #widget, #main').height(wh-hh-10);

	ww = parseInt($(window).width());
	mw = ww - parseInt($('#widget').width());
	$('#map').width(mw-3);
}

function loadBaiduMapScript()
{
	if (!baiduLoaded) {
		var script = document.createElement('script');
		script.src = 'http://api.map.baidu.com/api?v=1.3&callback=baiduMapCallback';
		document.body.appendChild(script);
		
		var trans_script = document.createElement('script');
		trans_script.src = 'http://dev.baidu.com/wiki/static/map/API/examples/script/convertor.js';
		document.body.appendChild(trans_script);

		baiduLoaded = true;
	}
}

$(function(){
	resizeDivs();
	$(window).resize(resizeDivs);

	loadBaiduMapScript();

	$('#btnSearch').click(function(){
		bs.search($('#keywords').val());
	});
});
</script>
</body>
</html>
<?php Msd_Output::doOutput();?>