<?php include_once dirname(__FILE__).'/../include/page_head.phtml';?>
<div class='wrapper'>
	<?php include_once(dirname(__FILE__).'/../include/page_info.phtml');?>
	<div class='page_nav'>
		<div class='page_info'>编辑文章分类</div>
		
		<div class='page_now'></div>
	</div>	

<form method='post' action='<?php echo $this->scriptUrl;?>articlecategory/doedit' target='_self'>	
<table class='edit_table' cellspacing='1'>
	<tbody>
		<tr>
			<td width='15%' class='center left'>
				分类名称
			</td>
			<td width='35%' class='text right'>
				<input type='text' name='CategoryName' id='CategoryName' value='<?php echo $this->data['CategoryName'];?>' /> <span class='error'><?php echo $this->error['CategoryName'];?></span>
			</td>
			<td width='15%' class='center left'>
				排序值
			</td>
			<td width='35%' class='text right'>
				<input type='text' maxlength='4' name='OrderNo' id='OrderNo' value='<?php echo $this->data['OrderNo'];?>' /><span class='error'><?php echo $this->error['OrderNo'];?></span>
			</td>
		</tr>
		
		<tr>
			<td colspan='4' class='center bottom'>
				<input type='submit' id='submit' value='确定' />
				<input type='hidden' name='CategoryId' value='<?php echo $this->data['CategoryId'];?>' id='CategoryId' />			
			</td>
		</tr>
	</tbody>
</table>
</div>
<?php include_once dirname(__FILE__).'/../include/page_foot.phtml';?>