<?php include_once dirname(__FILE__).'/../include/page_head.phtml';?>
<div class='wrapper'>
	<?php include_once(dirname(__FILE__).'/../include/page_info.phtml');?>
	<div class='page_nav'>
		<div class='page_info'>编辑Api</div>
		
		<div class='page_now'></div>
	</div>	

<form method='post' action='<?php echo $this->scriptUrl;?>api/doedit' target='_self'>	
<table class='edit_table' cellspacing='1'>
	<tbody>
		<tr>
			<td width='15%' class='center left'>
				Api Key
			</td>
			<td colspan='3' class='text right'>
				<input type='text' size='80' name='ApiKey' id='ApiKey' value='<?php echo $this->data['ApiKey'];?>' readonly='readonly' /> <span class='error'><?php echo $this->error['ApiKey'];?></span>
			</td>
		</tr>
		<tr>
			<td class='center left'>
				所有人
			</td>
			<td colspan='3' class='text right'>
				<input type='text' size='80' name='Owner' id='Owner' value='<?php echo $this->data['Owner'];?>' /> <span class='error'><?php echo $this->error['Owner'];?></span>
			</td>
		</tr>
		<tr>
			<td width='15%' class='center left'>
				每小时限额
			</td>
			<td class='text right'>
				<input type='text' size='6' name='VisitsPerHour' id='VisitsPerHour' value='<?php echo $this->data['VisitsPerHour'];?>' />
			</td>
			<td width='15%' class='center left'>
				每天限额
			</td>
			<td class='text right'>
				<input type='text' size='6' name='VisitsPerDay' id='VisitsPerDay' value='<?php echo $this->data['VisitsPerDay'];?>' />
			</td>			
		</tr>		
		<tr>
			<td colspan='4' class='center bottom'>
				<input type='submit' id='submit' value='确定' />
				<input type='button' id='back' value='返回' onclick="javascript:history.back()" />
				<input type='hidden' name='Id' value='<?php echo $this->data['Id'];?>' id='Id' />			
			</td>
		</tr>
	</tbody>
</table>
</form>
</div>
<?php include_once dirname(__FILE__).'/../include/page_foot.phtml';?>