<?php Msd_Output::prepareHtml();?>
<?php echo '<'.'?xml version="1.0" encoding="utf-8"?'.'>'."\n";?>
<!DOCTYPE html>
<html dir="ltr" lang="zh-CN" xmlns="http://www.w3.org/1999/xhtml"> 
<head>
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<meta http-equiv="expires" content="Wed, 26 Feb 1997 08:21:57 GMT" />
<meta http-equiv="pragma" content="no-cache" />
<meta http-equiv="Cache-Control" content="no-cache" />
<title><?php echo $this->MetaPara['title'];?></title>
<meta name="keywords" content="<?php echo $this->MetaPara['keywords'];?>" />
<meta name="description" content="<?php echo $this->MetaPara['description'];?>" />
<meta http-equiv="Content-Language" content="zh-CN" />
<meta name="google-site-verification" content="<?php echo $this->CityConfig->meta->google_site_verification;?>" />
<meta property="wb:webmaster" content="<?php echo $this->CityConfig->meta->wb_webmaster;?>" />
<meta property="qc:admins" content="<?php echo $this->CityConfig->meta->qc_admins;?>" />
<meta name="MSSmartTagsPreventParsing" content="true" />
<meta http-equiv="imagetoolbar" content="no" />
<meta name="author" content="江苏汇洋信息科技股份有限公司" />
<meta name="copyright" content="江苏汇洋信息科技股份有限公司" />
<base href="<?php echo $this->Basehref();?>" />
<link rel="search" type="application/opensearchdescription+xml" href="/opensearch.xml" title="<?php echo $this->MetaPara['title'];?>" />
<link rel="stylesheet" href="<?php echo $this->Basehref();?>common/css/styles.css?1<?php echo date('Ymd',filemtime("./common/css/styles.css"))?>" type="text/css" media="screen" />
<link rel="stylesheet" href="<?php echo $this->Basehref();?>common/css/formly.css?<?php echo date('Ymd',filemtime("./common/css/formly.css"))?>" type="text/css" />
<link rel="stylesheet" href="<?php echo $this->Basehref();?>common/css/colorbox.css?<?php echo date('Ymd',filemtime("./common/css/colorbox.css"))?>" />
<!--styles for IE -->
<!--[if lte IE 7]><link rel="stylesheet" href="<?php echo $this->Basehref();?>common/css/ie.css?<?php echo FANDIAN_APP_VER;?>" type="text/css" media="screen" /><![endif]-->
<!--styles -->
<script src="<?php echo $this->Basehref();?>common/js/jquery.min.js"></script>
<script src="<?php echo $this->Basehref();?>common/js/easing.js" type="text/javascript"></script>
<script src="<?php echo $this->Basehref();?>common/js/jquery.ui.totop.js" type="text/javascript"></script>
<script src="<?php echo $this->Basehref();?>common/js/slides.min.jquery.js" type="text/javascript"></script>
<script src='<?php echo $this->Basehref();?>common/js/jquery.autocomplete.js?<?php echo FANDIAN_APP_VER;?>' type='text/javascript'></script>
<script src="<?php echo $this->Basehref();?>common/js/main.js?<?php echo FANDIAN_APP_VER;?>" type="text/javascript"></script>
<script src="<?php echo $this->Basehref();?>common/js/jquery.colorbox-min.js"></script>
<script src='<?php echo $this->Basehref();?>common/js/scroll.js' type='text/javascript'></script>

<script type="text/javascript">
var FANDIAN_BASE_URL   = '<?php echo $this->baseUrl;?>';
var FANDIAN_SCRIPT_URL = '<?php echo $this->scriptUrl;?>';
var FANDIAN_STATIC_URL = '<?php echo Msd_Config::appConfig()->static_url;?>';
var CITY = {};
CITY.name = '<?php echo $this->CityConfig->name;?>';
CITY.longitude = '<?php echo $this->CityConfig->longitude;?>';
CITY.latitude = '<?php echo $this->CityConfig->latitude;?>';
<?php if ($this->need_scroll && $this->cName=='index' && $this->data['idx_sb']['url']) { ?>
AD = new ADM("FULL",0);
AD.StartTime    = new Array("2006/04/01 12:00");
AD.EndTime      = new Array("2020/04/01 12:00");
AD.src          = new Array("<?php echo $this->data['idx_sb']['url'];?>");
AD.href         = new Array("<?php echo $this->data['idx_sb']['link'] ? $this->data['idx_sb']['link'] : 'javascript:void(0)';?>");
AddSchedule(AD);
<?php } ?>
</script>
<script type="text/javascript" src="<?php echo $this->Basehref();?>common/js/library.js?<?php echo FANDIAN_APP_VER;?>" charset="utf-8"></script>
</head>
<body>
